# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcription.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13transcription.proto\x12\rtranscription\"%\n\x14TranscriptionRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"%\n\x15TranscriptionResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2e\n\nTranscribe\x12W\n\nTranscribe\x12#.transcription.TranscriptionRequest\x1a$.transcription.TranscriptionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIPTIONREQUEST']._serialized_start=38
  _globals['_TRANSCRIPTIONREQUEST']._serialized_end=75
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_start=77
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_end=114
  _globals['_TRANSCRIBE']._serialized_start=116
  _globals['_TRANSCRIBE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
