# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcription.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13transcription.proto\x12\rtranscription\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n\x11TranscribeRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\t\x12\x15\n\ris_long_audio\x18\x02 \x01(\x08\x12\x10\n\x08language\x18\x03 \x01(\t\"W\n\x12TranscribeResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2i\n\x14TranscriptionService\x12Q\n\nTranscribe\x12 .transcription.TranscribeRequest\x1a!.transcription.TranscribeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIBEREQUEST']._serialized_start=71
  _globals['_TRANSCRIBEREQUEST']._serialized_end=146
  _globals['_TRANSCRIBERESPONSE']._serialized_start=148
  _globals['_TRANSCRIBERESPONSE']._serialized_end=235
  _globals['_TRANSCRIPTIONSERVICE']._serialized_start=237
  _globals['_TRANSCRIPTIONSERVICE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
